export enum UserActions {
  CREATE_USER = 'USERS/CREATE_USER',
  CHANGE_AVATAR = 'USERS/CHANGE_AVATAR',
  UPDATE_USER = 'USERS/UPDATE_USER'
}

export enum ZipCodeActions {
  FETCH_ZIPADDRESS_START = 'USERS/ZIP_ADDRESS_START',
  FETCH_ZIPADDRESS_ERROR = 'USERS/ZIP_ADDRESS_ERROR',
  FETCH_ZIPADDRES_DONE = 'USERS/FETCH_ZIPADDRES_DONE'
}
